### ISSUE TITLE
Android 2.3 problem

### ISSUE THREAD

**Issue by ghost** [drgullin/icheck#3]
Tap of label area of "Line skin", cannot work on Android 2.3.5.

**Comment by drgullin** [comment]
Thanks, this issue is fixed. Tested on Android 1.5+.

**Comment by ghost** [comment]
This is still an issue in 4.2 Jelly Bean. The Line Skin cannot be clicked in Chrome. Tested on a Nexus 4.

The only way I have found to click it—which may help you solve it—is to slide up from the bottom of the button.
