### ISSUE TITLE
 Uncaught TypeError: this.$(...).iCheck is not a function

### ISSUE THREAD

**Issue by vishusharmagit** [drgullin/icheck#362]
Hi,

I am getting this error after npm update.

Can you please suggest something to solve it.

**Comment by iamsolarplexus** [comment]
If you're using 2.0, note that the method appears to be all lowercase now.

**Comment by vishusharmagit** [comment]
Thanks, I fixed it.

**Comment by codedcontainer** [comment]
I still get this issue even though I have it as lowercase. I've tried to add this to document.ready and even on a setTimeout. Will work in console not in code.

**Comment by vishusharmagit** [comment]
HI @jdmagic21,

If lowercase part is not working for you.
I suggest to move you 'jQuery' dependency up.

Regards,
Vishu
